# Form implementation generated from reading ui file 'about_pr.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecondDialog(object):
    def setupUi(self, SecondDialog):
        SecondDialog.setObjectName("SecondDialog")
        SecondDialog.resize(684, 485)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        SecondDialog.setFont(font)
        self.label = QtWidgets.QLabel(parent=SecondDialog)
        self.label.setGeometry(QtCore.QRect(70, 160, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=SecondDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 301, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("фото/ccc.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=SecondDialog)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 750, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=SecondDialog)
        self.label_4.setGeometry(QtCore.QRect(290, 50, 375, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(parent=SecondDialog)
        self.pushButton.setGeometry(QtCore.QRect(550, 430, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(143, 209, 104);\n"
"border-color: rgb(15, 15, 15);\n"
"border-radius: 20px;\n"
"font-size:20px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_14 = QtWidgets.QLabel(parent=SecondDialog)
        self.label_14.setGeometry(QtCore.QRect(410, 410, 55, 16))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.textEdit = QtWidgets.QTextEdit(parent=SecondDialog)
        self.textEdit.setGeometry(QtCore.QRect(300, 60, 371, 291))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(parent=SecondDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 251, 251))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("фото/sob.png"))
        self.label_5.setObjectName("label_5")

        self.pushButton.clicked.connect(SecondDialog.close)

        self.retranslateUi(SecondDialog)
        QtCore.QMetaObject.connectSlotsByName(SecondDialog)

    def retranslateUi(self, SecondDialog):
        _translate = QtCore.QCoreApplication.translate
        SecondDialog.setWindowTitle(_translate("SecondDialog", "О программе"))
        self.label_3.setText(_translate("SecondDialog", "Приложение напоминаний о памятных датах"))
        self.pushButton.setText(_translate("SecondDialog", "НАЗАД"))
        self.textEdit.setHtml(_translate("SecondDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">Программа позволяет:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">1. Устанавливать памятную дату.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">2. Устанавливать напоминания на определенный день и время.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">3. Доступ к памятным датам.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">4. Управление списком дат (редактирование).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">5. Поиск памятных дней (год или дата или название).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">6. Вывод уведомления ползователю о памятной дате.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">7. Давать пользователю возможность о отметке, что дата прошла или об отменене.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">8. Сохранение памятных дат от пользвателя в бд или файле.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">9. При запуске программы сохранять раннее заполненные даты/данные.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">10. (Возможна отправка по электронной почте).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#141414;\">11. Возможно изменение настроек(текста, цвет), открытие файлов.</span></p></body></html>"))

#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     SecondDialog = QtWidgets.QDialog()
#     ui = Ui_SecondDialog()
#     ui.setupUi(SecondDialog)
#     SecondDialog.show()
#     sys.exit(app.exec())
