# Form implementation generated from reading ui file 'author.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FirstDialog(object):
    def setupUi(self, FirstDialog):
        FirstDialog.setObjectName("FirstDialog")
        FirstDialog.resize(449, 488)
        self.label_2 = QtWidgets.QLabel(parent=FirstDialog)
        self.label_2.setGeometry(QtCore.QRect(190, 300, 191, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=FirstDialog)
        self.label_3.setGeometry(QtCore.QRect(100, 330, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=FirstDialog)
        self.label_4.setGeometry(QtCore.QRect(100, 370, 411, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=FirstDialog)
        self.label_5.setGeometry(QtCore.QRect(110, 400, 361, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=FirstDialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 440, 191, 41))
        self.pushButton.setStyleSheet("background-color: rgb(143, 209, 104);\n"
"border-color: rgb(15, 15, 15);\n"
"border-radius: 20px;\n"
"font-size:20px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=FirstDialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 351, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("фото/author.png"))
        self.label.setObjectName("label")

        self.pushButton.clicked.connect(FirstDialog.close)
        self.retranslateUi(FirstDialog)
        QtCore.QMetaObject.connectSlotsByName(FirstDialog)

    def retranslateUi(self, FirstDialog):
        _translate = QtCore.QCoreApplication.translate
        FirstDialog.setWindowTitle(_translate("FirstDialog", "O авторе"))
        self.label_2.setText(_translate("FirstDialog", "Автор"))
        self.label_3.setText(_translate("FirstDialog", "Студентка группы 10701222"))
        self.label_4.setText(_translate("FirstDialog", "Бондарь Юлия Владимировна"))
        self.label_5.setText(_translate("FirstDialog", "uliabondar359@gmail.com"))
        self.pushButton.setText(_translate("FirstDialog", "НАЗАД"))

#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     FirstDialog = QtWidgets.QDialog()
#     ui = Ui_FirstDialog()
#     ui.setupUi(FirstDialog)
#     FirstDialog.show()
#     sys.exit(app.exec())
