# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_eForm(object):
    def setupUi(self, eForm):
        eForm.setObjectName("eForm")
        eForm.resize(450, 350)
        eForm.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton = QtWidgets.QPushButton(parent=eForm)
        self.pushButton.setGeometry(QtCore.QRect(340, 300, 93, 41))
        self.pushButton.setStyleSheet("background-color: rgb(153, 227, 113);\n"
"border-color: rgb(9, 9, 9);\n"
"border-width: thick;\n"
"border-radius:20px;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=eForm)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=eForm)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 30, 431, 131))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(parent=eForm)
        self.label.setGeometry(QtCore.QRect(10, 170, 291, 171))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("фото/error.png"))
        self.label.setObjectName("label")

        self.pushButton.clicked.connect(eForm.close)
        self.retranslateUi(eForm)
        QtCore.QMetaObject.connectSlotsByName(eForm)

    def retranslateUi(self, eForm):
        _translate = QtCore.QCoreApplication.translate
        eForm.setWindowTitle(_translate("eForm", "Ошибка программы"))
        self.pushButton.setText(_translate("eForm", "Назад"))
        self.label_2.setText(_translate("eForm", "Если у вас \"Ошибка программы\":"))
        self.plainTextEdit.setPlainText(_translate("eForm", "1. Проверьте правильность ввода даты.\n"
"2. Перезапустите программу.\n"
"3. Убедитесь, что вы указали корректные данные для напоминания. \n"
"4. Проверьте наличие поддержки операционной системы.\n"
"5. Проверьте наличие достаточных ресурсов устройства. убедитесь, что у вас достаточно свободного пространства и производительности на устройстве."))

#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     eForm = QtWidgets.QWidget()
#     ui = Ui_eForm()
#     ui.setupUi(eForm)
#     eForm.show()
#     sys.exit(app.exec())
