# Form implementation generated from reading ui file 'prilo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_cal_Window(object):
    def setupUi(self, Main_cal_Window):
        Main_cal_Window.setObjectName("Main_cal_Window")
        Main_cal_Window.resize(750, 593)
        self.centralwidget = QtWidgets.QWidget(parent=Main_cal_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 0, 700, 41))
        font = QtGui.QFont()
        font.setFamily("Niagara Engraved")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(350, 80, 381, 361))
        self.calendarWidget.setObjectName("calendarWidget")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(350, 450, 400, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 100, 321, 331))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20
                                              , 60, 201, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(13)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 450, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(10, 450, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 510, 750, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Main_cal_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main_cal_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menubar.setObjectName("menubar")
        Main_cal_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main_cal_Window)
        self.statusbar.setObjectName("statusbar")
        Main_cal_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_cal_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_cal_Window)

    def retranslateUi(self, Main_cal_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_cal_Window.setWindowTitle(_translate("Main_cal_Window", "Приложение напоминаний о памятных датах"))
        self.label.setText(_translate("Main_cal_Window", "Приложение напоминаний о памятных датах"))
        self.label_2.setText(_translate("Main_cal_Window", "Опишите событие"))
        self.pushButton.setText(_translate("Main_cal_Window", "Отследить"))
        self.label_3.setText(_translate("Main_cal_Window", "До наступления события осталось:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_cal_Window = QtWidgets.QMainWindow()
    ui = Ui_Main_cal_Window()
    ui.setupUi(Main_cal_Window)
    Main_cal_Window.show()
    sys.exit(app.exec())

